version: "3.0"

services:

  backend:
    build: .
    container_name: backend
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=4
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media_django:/app/media
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    container_name: nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend
